Generate data
htmlacademy-javascript/907509-keksobooking-23 pull request #3
Opened 2021-06-12 06:28 UTC by Amanter

2021-06-14 07:41 UTC, 4err requested changes

2021-06-15 05:17 UTC, 4err requested changes

2021-06-15 05:17 UTC, 4err commented on js/main.js
> +  const AvatarNumber = num <= 10 ? `0${num}` : num;
С заглавной буквы именуются конструкторы и классы. А также все еще магические числа, кажется ты пропустил замечание про них. Здесь и далее.

2021-06-15 05:17 UTC, 4err commented on js/main.js
> +    randomAdd: {
Почему `randomAdd`, если у нас есть конкретное название этого свойства?

2021-06-15 05:17 UTC, 4err commented on js/main.js
> +      features: getArrayRandElement(FEATURES),
Здесь и в фото. Это должен быть массив случайной длинны со случайным количеством элементов, а не один случайный элемент массива.

2021-06-15 08:32 UTC, Amanter commented on js/main.js
> +    randomAdd: {
ой точно

2021-06-15 08:33 UTC, Amanter commented on js/main.js
> +  const AvatarNumber = num <= 10 ? `0${num}` : num;
тупанул с названием).......... ок, переберу значения от 1 до 10 через цикл!!!!!!

2021-06-15 08:37 UTC, Amanter commented on js/main.js
> +      features: getArrayRandElement(FEATURES),
а вот тут частично не соглашусь. В ДЗ четко было обозначено , что guest это (Случайное целое положительное число.), далее checkin/chekout (строка — одно из трёх фиксированных значений). А вот features и photos, согласен - это массив случайной длины!

2021-06-15 09:11 UTC, Amanter commented on js/main.js
> +  const AvatarNumber = num <= 10 ? `0${num}` : num;
правда мне кажется что не верно решение

2021-06-22 06:50 UTC, merged